version: '3.7'

services:
  speedtest:
    container_name: speedtest
    build: ./librespeed
    restart: always
    environment:
      MODE: ${MODE}
      BACKENDPORT: ${BACKENDPORT}
      TELEMETRY_LEVEL: ${TELEMETRY_LEVEL}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_TABLE: ${DB_TABLE}
      TELEMETRY_INTERVAL: ${TELEMETRY_INTERVAL}
      TELEMETRY_RETENTION: ${TELEMETRY_RETENTION}
      TELEMETRY_MAX_ROWS: ${TELEMETRY_MAX_ROWS}
      TELEMETRY_CLEANUP_INTERVAL: ${TELEMETRY_CLEANUP_INTERVAL}
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: netscope-backend
    build: ./backend
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      LIBRESPEED_HOST: ${LIBRESPEED_HOST}
      LIBRESPEED_PORT: ${LIBRESPEED_PORT}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      speedtest:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  postgres_data: