# railway.toml

[[services]]
# Speedtest (Librespeed) Service
serviceId = "speedtest"
build = { dockerfilePath = "librespeed/Dockerfile" }
environment = [
  { MODE = "backend" },
  { BACKENDPORT = "8081" },
  { TELEMETRY_LEVEL = "basic" },
  { DB_TYPE = "postgres" },
  { DB_HOST = "postgres.railway.internal" },
  { DB_PORT = "5432" },
  { DB_NAME = "" }, # Set via Railway dashboard
  { DB_USER = "" }, # Set via Railway dashboard
  { DB_PASSWORD = "" }, # Set via Railway dashboard
  { DB_TABLE = "speedtest_users" },
  { TELEMETRY_INTERVAL = "60" },
  { TELEMETRY_RETENTION = "30" },
  { TELEMETRY_MAX_ROWS = "1000000" },
  { TELEMETRY_CLEANUP_INTERVAL = "24" }
]
autoDeploy = true
healthcheck = { method = "GET", path = "/health", port = 8081 }

[[services]]
# PostgreSQL Service
serviceId = "postgres"
image = "postgres:15"
environment = [
  { POSTGRES_DB = "" }, # Set via Railway dashboard
  { POSTGRES_USER = "" }, # Set via Railway dashboard
  { POSTGRES_PASSWORD = "" } # Set via Railway dashboard
]
autoDeploy = true
# Enable volume in Railway dashboard for persistent storage

[[services]]
# Backend (Express API) Service
serviceId = "backend"
build = { dockerfilePath = "./backend/Dockerfile" }
environment = [
  { NODE_ENV = "production" },
  { PORT = "3000" },
  { DATABASE_URL = "${{ Postgres.DATABASE_URL }}" }, # Use Railway's connection string
  { LIBRESPEED_HOST = "speedtest.railway.internal" }, # Use internal hostname
  { LIBRESPEED_PORT = "8081" }
]
autoDeploy = true
dependsOn = ["postgres", "speedtest"] # Ensures deployment order
healthcheck = { method = "GET", path = "/health", port = 3000 }

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3